### ISSUE TITLE
sendKeys command fails with 500 status

### ISSUE THREAD

**Issue by suryak-cs** [AppiumTestDistribution/flutter-finder#8] opened 2024-07-19 17:33 UTC
While playing with the FlutterByTests.java, it looks like the elements are being identified correctly, but some actions like sendKeys() fails with 500 error. This is most likely due to wrong payload being constructed and sent to the server

```
POST /session/accb4550-9c83-4892-9e74-e605539be3ff/element/921945a9-2194-5a92-1945-a921945a9219/value {"id":"921945a9-2194-5a92-1945-a921945a9219","value":["a","d","m","i","n"],"text":"admin"}
[accb4550][38;5;-164m[AppiumFlutterDriver@e63b] Calling AppiumDriver.setValue() with args: [["a","d","m","i","n"],"921945a9-2194-5a92-1945-a921945a9219","accb4550-9c83-4892-9e74-e605539be3ff"]
[accb4550][WD Proxy] Matched '/element/921945a9-2194-5a92-1945-a921945a9219/value' to command name 'setValue'
[accb4550][Protocol Converter] Added 'value' property ["a","d","m","i","n"] to 'setValue' request body
[accb4550][WD Proxy] Proxying [POST /element/921945a9-2194-5a92-1945-a921945a9219/value] to [POST http://127.0.0.1:9001/session/a6d1fa1c-078e-4d05-8b94-8834610354a7/element/921945a9-2194-5a92-1945-a921945a9219/value] with body: {"text":["a","d","m","i","n"],"value":["a","d","m","i","n"]}
[accb4550][WD Proxy] Got response with status 500: {"sessionId":"a6d1fa1c-078e-4d05-8b94-8834610354a7","value":{"error":"unknown error","message":"type 'List<dynamic>' is not a subtype of type 'String' in type cast","stackTrace":"#0      _$SetTextModalFromJson (package:appium_flutter_server/src/models/api/generated/set_text.g.dart:10:26)\n#1      new SetTextModal.fromJson (package:appium_flutter_server/src/models/api/set_text.dart:14:7)\n#2      SetTextHandler.handle (package:appium_flutter_server/src/handler/set_text.dart:18:46)\n<asynchronous suspension>\n#3      RequestHandler.getHandler.<anonymous closure> (package:appium_flutter_server/src/handler/request/request_handler.dart:30:35)\n<asynchronous suspension>\n#4      _RouterPlusHandler._handler (package:shelf_plus/src/router_plus/router_plus.dart:64:16)\n<asynchronous suspension>\n#5      RouterEntry.invoke.<anonymous closure> (package:shelf_router/src/router_entry.dart:107:16)\n<asynchronous suspension>\n#6      RouterEntry.invoke (package:shelf_router/src/router_entry.dart:104:12)\n<asynchronous su...
[accb4550][W3C] Matched W3C error code 'unknown error' to UnknownError
[accb4550][38;5;-164m[AppiumFlutterDriver@e63b] Encountered internal error running command: UnknownError: An unknown server-side error occurred while processing the command. Original error: type 'List<dynamic>' is not a subtype of type 'String' in type cast
    at errorFromW3CJsonCode (/Users/MOHAPSX18/.appium/node_modules/appium-flutter-integration-driver/node_modules/@appium/base-driver/lib/protocol/errors.js:1112:25)
    at ProxyRequestError.getActualError (/Users/MOHAPSX18/.appium/node_modules/appium-flutter-integration-driver/node_modules/@appium/base-driver/lib/protocol/errors.js:981:14)
    at JWProxy.command (/Users/MOHAPSX18/.appium/node_modules/appium-flutter-integration-driver/node_modules/@appium/base-driver/lib/jsonwp-proxy/proxy.js:353:19)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at AppiumFlutterDriver.setValue (/Users/MOHAPSX18/.appium/node_modules/appium-flutter-integration-driver/build/src/commands/element.js:70:12)
[accb4550][HTTP] <-- POST /session/accb4550-9c83-4892-9e74-e605539be3ff/element/921945a9-2194-5a92-1945-a921945a9219/value 500 49 ms - 1111 

An unknown server-side error occurred while processing the command. Original error: type 'List<dynamic>' is not a subtype of type 'String' in type cast

``` 

The body should be 
```
{
    "text": "admin"
}
```

while the one currently sent is 

`{"text":["a","d","m","i","n"],"value":["a","d","m","i","n"]}`

**Comment by sudharsan-selvaraj** [comment] 2024-07-19 17:46
The issue is already addressed in https://github.com/AppiumTestDistribution/appium-flutter-server/pull/19

You are using a older version of flutter server package to build the app instance. Kindly use the latest version (`0.0.21` as of today) and rebuild the app.

**Closed as completed by sudharsan-selvaraj** 2024-07-19 17:46 UTC
